// <auto-generated />
using MiBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiBackend.Data.Migrations
{
    [DbContext(typeof(MiBackendContext))]
    partial class MiBackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiBackend.Domain.Entities.Chico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MicroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("MicroId");

                    b.ToTable("Chicos");
                });

            modelBuilder.Entity("MiBackend.Domain.Entities.Chofer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MicroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("MicroId")
                        .IsUnique();

                    b.ToTable("Choferes");
                });

            modelBuilder.Entity("MiBackend.Domain.Entities.Micro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Micros");
                });

            modelBuilder.Entity("MiBackend.Domain.Entities.Chico", b =>
                {
                    b.HasOne("MiBackend.Domain.Entities.Micro", "Micro")
                        .WithMany("Chicos")
                        .HasForeignKey("MicroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Micro");
                });

            modelBuilder.Entity("MiBackend.Domain.Entities.Chofer", b =>
                {
                    b.HasOne("MiBackend.Domain.Entities.Micro", "Micro")
                        .WithOne("Chofer")
                        .HasForeignKey("MiBackend.Domain.Entities.Chofer", "MicroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Micro");
                });

            modelBuilder.Entity("MiBackend.Domain.Entities.Micro", b =>
                {
                    b.Navigation("Chicos");

                    b.Navigation("Chofer");
                });
#pragma warning restore 612, 618
        }
    }
}
